### ISSUE TITLE
TODO and Ideas

### ISSUE THREAD

**Issue by ImagicalGamer** [ImagicalGamer/EconomyPlus#1]
Comment with ideas!!!

**Comment by ImagicalGamer** [comment]
#Squad @TheDragonRing @Taki21 @remotevase I need ideas for the main plug, I'm starting on shops (need MAJOR halp with) and jobs

**Comment by remotevase** [comment]
Since stuff that Economy API also has, +exclusive features

**Comment by ImagicalGamer** [comment]
I will add sellhand!

**Comment by ImagicalGamer** [comment]
:cry:

**Comment by TheDragonRing** [comment]
What about adding a /factory command? I know it would be really hard, but we could just do like it spawns a hopper somewhere, and as long as the player keeps putting, say, wheat (or we could make it configurable) in the hopper they earn 300 every 15 minutes?

**Comment by remotevase** [comment]
OFF TOPIC: @ImagicalGamer @Taki21 @applqpak @ImagicalCorp\im-team plz accept my invite to https://github.com/Inactive-to-Reactive

**Comment by ImagicalGamer** [comment]
done

**Comment by ImagicalGamer** [comment]
That would be cool the hopper idea

**Comment by Thunder33345** [comment]
hmm is that supposed to be in core of a branch off form core

**Comment by ImagicalGamer** [comment]
wat? the hopper idea? and MCPE doesn't have hoppers as of 0.14.3 but 0.15 does?

**Comment by ImagicalGamer** [comment]
@TheDragonRing just added factory, all that's needed is a pay system for it and maybe item spawning

**Comment by ImagicalGamer** [comment]
We could do item spawning, prevent the blocks that are factorys from being broken and save the coords to a file and spawn an item that can be redeemed ever x min for x amount of cash

**Comment by Thunder33345** [comment]
against my better judgement the core and the extra should be separated so in the end it wont be full of unorganized chaos

**Comment by ImagicalGamer** [comment]
:+1: I will make them separate

**Comment by ImagicalGamer** [comment]
I put out a beta release on IM forums, we need this tested in production servers so we can make it better and more bug free.

**Comment by ImagicalGamer** [comment]
Adding multi-language support

**Comment by remotevase** [comment]
Great!!!!

**Comment by TheDragonRing** [comment]
Off-Topic: @ImagicalGamer I'm adding some economy features into BOB using a mixture of modified code from both this & EconomyS

**Comment by SoyPro** [comment]
and where are the permissions?

**Comment by SoyPro** [comment]
i need perms for my groups

**Comment by SoyPro** [comment]
A future you can add is like a auction,like bukkit in floauction for example [AUC] player is selling 24 cobblestone for 1:00 minutes.and then an another message:

**Comment by Taki21** [comment]
@ImagicalGamer  ADD CREDIT AND DEBIT!
Credit or Debit...
*Slides card on neck* xD

**Comment by remotevase** [comment]
> @ImagicalGamer ADD CREDIT AND DEBIT!
Credit or Debit...
Slides card on neck xD

School Teacher: What do you prefer? School or work?
My Friend: Obviously work, because you get payed!
School teacher: But you do get payed at school! You get payed with knowledge!
My Other Friend: If that is so, then picture this. You are buying something from a store. They ask "cash, credit, or debit?" and you say "None, thanks. I'm going to pay with knowledge". 

Put emphasis on "knowledge" and it will be hilarious

**Comment by Taki21** [comment]
LOL

**Comment by ImagicalGamer** [comment]
LMAO

**Comment by ImagicalGamer** [comment]
ADDING CREDIT CARDS!!!

**Comment by ImagicalGamer** [comment]
Do we want to use saddles as "wallets" or debit/credit cards?

**Comment by remotevase** [comment]
Saddles? U talking about a 0.15 Server world where everything is implemented immediately? You are living a fantasy then...

**Comment by ImagicalGamer** [comment]
xD we need an un-used item or to make a new one

**Comment by ImagicalGamer** [comment]
I'm gonna try the same concept used to make items in PocketMine but use the data of another item etc bla bla bla

**Comment by remotevase** [comment]
How about you get a common item (like a slab) and rename it?

**Comment by ImagicalGamer** [comment]
u so smart xD

**Comment by ImagicalGamer** [comment]
@Thunder33345 can u start on a CreditCard or DebitCard system pls? I can link da items but idk where to start with dose.

**Comment by ImagicalGamer** [comment]
@SoyPro adding perms..... later xD

**Comment by Taki21** [comment]
Ur welcome @ImagicalGamer : )

**Comment by Thunder33345** [comment]
@ImagicalGamer idk what if someone already working on it and what is the concept/usage?

**Comment by Thunder33345** [comment]
well that means like multiple accounts which is...
hassle lets just say

**Comment by ImagicalGamer** [comment]
Yea we could use the same YAML system I used in ImagicalAuth and move all player data to their own files so we can have credit card data etc

**Comment by TheDragonRing** [comment]
I posted an idea in the IMCF thread, in case you didn't see: When a player is given money with /pay they get a 'cheque' (renamed paper), then if they do /redeem they lose the cheque and recieve the money. The cheque/paper is actually rename to '$AmountOfMoneyPayed Cheque'

**Comment by Thunder33345** [comment]
idk i think it is kinda pushing things
is the main functions done?
and idk maybe the checks cards should be a separate plugin that communicate to core using APIs?

**Comment by ImagicalGamer** [comment]
Main functions are done, we should move credit and debit cards to a separate plug, I luv the paper think kinda like withdrawl on IM forums?

**Comment by SoyPro** [comment]
please add that we can make a shop in a sign
