### ISSUE TITLE
Add Item Name Option to Shop Signs

### ISSUE THREAD

**Issue by caspervanneck** [ImagicalGamer/EconomyPlus#12]
can you add item naam and fix syntax

**Comment by ImagicalGamer** [comment]
Yes I can add the option for item names or item ID's on shop/sell signs

**Comment by ImagicalGamer** [comment]
@remotevase Win10 MCPE is broken for me can you test and see if using an item name instead of ID on shop/sell signs works? I use ```php Item::fromString(); ``` so it might work

**Comment by remotevase** [comment]
@ImagicalGamer Win10 is broken for me as well, and my MCPE version is 0.16, and my server version is 0.15

**Comment by remotevase** [comment]
Oh, and i can't downgrade my MCPE because the game crashes every time thati open it (no matter what version, but only happens on 0.15.x)

**Comment by Taki21** [comment]
u guys are lucky.... i have 6 hours of hw each day

**Comment by Taki21** [comment]
or 613 lbs of homework

**Comment by Taki21** [comment]
oh @remotevase to fix that...
u MUST have ES file explorer. Delete your "games" folder. Install: 0.15 MCPE

**Comment by remotevase** [comment]
@Taki21 already tried that... Only MCPE 0.16 works. BTW: 8th grade has less homework than 7th grade... That's why I didn't like 7th grade, but I love 8th grade

**Comment by Taki21** [comment]
ya ik our teachers told us... xD

**Comment by ImagicalGamer** [comment]
Added with latest commit
