### ISSUE TITLE
Feature Request 

### ISSUE THREAD

**Issue by linuzo** [ImagicalGamer/EconomyPlus#29]
I would like to request a feature to allow full MySQL support so that we can have more options to use with web applications as well.

**Comment by remotevase** [comment]
we will try. @ImagicalGamer take a look at other sql compatible plugins for examples... like plugswork

**Comment by ImagicalGamer** [comment]
I'll make a fork of EconomyPlus that only has MySQL support

**Comment by ImagicalGamer** [comment]
@linuzo I'm working on MySQL support, I apologize for the slow progress.

**Comment by ImagicalGamer** [comment]
Added b741f3a8aa2f593fee08172cbad544f546
