### ISSUE TITLE
Commands don't works

### ISSUE THREAD

**Issue by HydrexHD** [ImagicalGamer/EconomyPlus#35]
### Issue description

commands don't works
  
### Steps to reproduce the issue

1. start the server
2. insert the command /mymoney

### OS and versions

* Version:
* PHP: 7.0
* OS: 0.1.5

### Crashdump, backtrace or other files

* [17:58:12] [Server thread/CRITICAL]: Unhandled exception executing command 'mymoney' in bal: Call to a member function sendMessage() on null
[17:58:12] [Server thread/CRITICAL]: Error: "Call to a member function sendMessage() on null" (EXCEPTION) in "/EconomyPlus-master/src/EconomyPlus/Commands/BalanceCommand" at line 32

**Comment by ImagicalGamer** [comment]
@HydrexHD here's the download for the latest commit: https://poggit.pmmp.io/r/298/EconomyPlus.phar
