### ISSUE TITLE
erors on death

### ISSUE THREAD

**Issue by caspervanneck** [ImagicalGamer/EconomyPlus#39]
### Issue description

1. kill a player
2. or do /kill and it wont work

### OS and versions

* Version:
* PHP: 7.0.3
* OS: linux

### Crashdump, backtrace or other files

*pocketmine\Player::getFinalDamageCause()" (EXCEPTION) in "/EconomyPlus_v0.1.5.phar/src/EconomyPlus/EventListener" at line 40
29.01 04:13:10 [Server] Server thread/CRITICAL "Could not pass event 'pocketmine\event\player\PlayerDeathEvent' to 'EconomyPlus v0.1.5': Call to undefined method pocketmine\Player::getFinalDamageCause() on EconomyPlus\EventListener

**Comment by ImagicalGamer** [comment]
Irrelevant, your not using the latest build. Death Money was removed from the EconomyPlus Core
