### ISSUE TITLE
cant make sign on letest version

### ISSUE THREAD

**Issue by caspervanneck** [ImagicalGamer/EconomyPlus#40]
### Issue description
cant make any sign on de latest version

### Steps to reproduce the issue

1. make a shop sign
2. ...

### OS and versions

* Version:
* PHP: 7.0.3
* OS: linux

### Crashdump, backtrace or other files

*no erors or crashing

**Comment by ImagicalGamer** [comment]
Please use the latest Poggit build, you may be using an outdated build.
