### ISSUE TITLE
Problem with /bal

### ISSUE THREAD

**Issue by XFizzer** [ImagicalGamer/EconomyPlus#41]
17.03 21:04:39 [Server] INFO Notice: Undefined property: EconomyPlus\EconomyPlus::$provider in phar:///plugins/EconomyPlus.phar/src/EconomyPlus/EventListener.php on line 32
17.03 21:04:39 [Server] INFO Notice: Accessing static property EconomyPlus\EconomyPlus::$provider as non static in phar:///plugins/EconomyPlus.phar/src/EconomyPlus/EventListener.php on line 32

**Comment by ImagicalGamer** [comment]
Fixed in latest commit.

**Comment by freescarab117** [comment]
is the Problem fixed with \bal
