### ISSUE TITLE
Infinite Money Bug

### ISSUE THREAD

**Issue by Jorti1** [ImagicalGamer/EconomyPlus#5]
I own a faction server and it came to my attention how players has millions if dollars after the first few days of the server opening. I play with he plugin a bit and do /pay Jorti1 100000 and it actually gives me 100000 even though I don't have that amount, I had around 1.4k

**Comment by ImagicalGamer** [comment]
@Jorti1 Can you test with the latest commit?

**Comment by Jorti1** [comment]
Ok, do I just download the zip from GitHub? Also will this mess up my shops?

**Comment by ImagicalGamer** [comment]
I will send a link to a phar, it won't delete any data.

**Comment by ImagicalGamer** [comment]
@Jorti1 Download [here](http://pmt.mcpe.me/data/phars/phar_EconomyPlus-master(1)_SXn2_Y0xns6wpp8.phar)

**Comment by Jorti1** [comment]
Ok, ty

**Comment by ImagicalGamer** [comment]
@Jorti1 Link was broken: [heres a new one](https://www.dropbox.com/s/i5iu0l9d6li84va/phar_EconomyPlus-master%281%29_7rqsGuj_Xkgewkd.phar?dl=0)

**Comment by Jorti1** [comment]
Seems to have not worked, would you like a screenshot?

**Comment by Jorti1** [comment]
https://drive.google.com/file/d/0B4nF6fIPfnKsaWFvZVZNRVFfaUU/view?usp=drivesdk

As you see, I did /bal.
Then I did /pay Jorti1
Then I did /bal and my balance has changed, I also reset the player money for everyone so I have no clue why this is happening and a few players know about it.

**Comment by Jorti1** [comment]
If you yourself would like to get on my server to check it out and see if it is true or not, you can ask me for the server Ip

**Comment by ImagicalGamer** [comment]
Try with the latest commit, it was a simple mistake when checking the players name.

**Comment by ImagicalGamer** [comment]
@Jorti1 https://www.dropbox.com/s/6src63cmp6zxx0g/phar_EconomyPlus-master_U2xiR_tQSbizsAv.phar?dl=0

**Comment by Jorti1** [comment]
Going so crazy, download the zip then a min later get the phar link...

I prefer the phar over zip though

**Comment by Jorti1** [comment]
Hhhmm, not sure but it now says invalid player although still gives me
money. Maybe if you add something that blocks their username from being
payed as the same user or block player from paying themselves

https://drive.google.com/file/d/0B4nF6fIPfnKsWGprQTJJVWZLc2c/view?usp=drivesdk

On Sep 12, 2016 5:34 PM, "Jorti1boombox" <phtcextara@gmail.com> wrote:

Going so crazy, download the zip then a min later get the phar link...

I prefer the phar over zip though

**Comment by ImagicalGamer** [comment]
@Jorti1 fixed now

**Comment by Jorti1** [comment]
Ok, will wait for a phar

**Comment by ImagicalGamer** [comment]
@Jorti1 https://www.dropbox.com/s/1a3xkfq4d6p9s6u/phar_EconomyPlus-master_rEW2RdfIoTGzsmm.phar?dl=0

**Comment by remotevase** [comment]
wow @ImagicalGamer awesomely fast bugfixing... How could you ever have thought of leaving?!?!?!

**Comment by Jorti1** [comment]
something apeared in consle this time, i hope this might help you find the issue....

[Server] [01:02:58] [Server thread/CRITICAL]: Unhandled exception executing command 'pay jorti1 100000000000000' in pay: Argument 1 passed to EconomyPlus\EconomyPlayer::pay() must be of the type integer, string given, called in /storage/emulated/0/PocketMine/plugins/EconomyPlus-master/src/EconomyPlus/Commands/PayMoneyCommand.php on line 53
[Server] [01:02:58] [Server thread/CRITICAL]: TypeError: "Argument 1 passed to EconomyPlus\EconomyPlayer::pay() must be of the type integer, string given, called in /storage/emulated/0/PocketMine/plugins/EconomyPlus-master/src/EconomyPlus/Commands/PayMoneyCommand.php on line 53" (EXCEPTION) in "/EconomyPlus-master/src/EconomyPlus/EconomyPlayer" at line 69
>

**Comment by ImagicalGamer** [comment]
@remotevase xP

**Comment by ImagicalGamer** [comment]
@Jorti1 Someone is using a word/letter instead of a number when paying someone

**Comment by ImagicalGamer** [comment]
Issue(s) resolved, Issue Closed

**Comment by Jorti1** [comment]
I don't clearly understand, I do this command to pay people....

/Pay {Player} {Amount}

**Comment by ImagicalGamer** [comment]
@Jorti1 /pay (amount) (player)

**Comment by ImagicalGamer** [comment]
Wait I need to fix some stuff @Jorti1 /pay (player) (amount)
